# DOCKER COMPOSE - Orchestrates all services and dependencies
# WHY? Single command to run entire platform: docker-compose up

version: "3.8"

services:
  # ===================================
  # DATABASE: PostgreSQL for User Service
  # ===================================
  postgres:
    image: postgres:16-alpine # Alpine = smaller image
    container_name: elearning-postgres
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      # SECURITY: In production, use Docker secrets, not plain text!
    ports:
      - "5432:5432" # Host:Container - access from localhost:5432
    volumes:
      # Persist data outside container (survives container restart)
      - postgres-data:/var/lib/postgresql/data
      # Init script (create tables on first run) - we'll add later
      # - ./scripts/init-postgres.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - elearning-network
    healthcheck:
      # Docker checks if PostgreSQL is ready
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ===================================
  # DATABASE: MongoDB for Course Service
  # ===================================
  mongodb:
    image: mongo:7-jammy # MongoDB 7 on Ubuntu Jammy
    container_name: elearning-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: elearning_courses_db
    ports:
      - "27018:27017" # Host:Container - avoid conflict with existing MongoDB on 27017
    volumes:
      # Persist MongoDB data
      - mongodb-data:/data/db
    networks:
      - elearning-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # ===================================
  # API GATEWAY
  # ===================================
  api-gateway:
    build:
      context: . # Build from root (needs parent POM)
      dockerfile: api-gateway/Dockerfile
    container_name: elearning-api-gateway
    ports:
      - "8080:8080" # Main entry point for all API requests
    environment:
      # Route to user service
      SPRING_CLOUD_GATEWAY_ROUTES_0_URI: http://user-service:8081
      # JWT secret (must match user-service)
      JWT_SECRET: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    depends_on:
      - user-service # Wait for user service to be ready
    networks:
      - elearning-network
    restart: unless-stopped

  # ===================================
  # USER SERVICE
  # ===================================
  user-service:
    build:
      context: . # Build from root (needs parent POM)
      dockerfile: user-service/Dockerfile
    container_name: elearning-user-service
    ports:
      - "8081:8081" # Expose to host machine
    environment:
      # Override application.yml settings
      SPRING_PROFILES_ACTIVE: dev # Use application-dev.yml
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/userdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      # WHY postgres as hostname? Docker Compose creates network, services resolve by name
    depends_on:
      postgres:
        condition: service_healthy # Wait for PostgreSQL to be ready
        # WHY? Service won't start until DB is healthy
    networks:
      - elearning-network
    restart: unless-stopped # Auto-restart if crashes
    # Uncomment for live code reload during development
    # volumes:
    #   - ./user-service/src:/app/src

  # ===================================
  # COURSE SERVICE
  # ===================================
  course-service:
    build:
      context: . # Build from root (needs parent POM)
      dockerfile: course-service/Dockerfile
    container_name: elearning-course-service
    ports:
      - "8082:8082" # Expose to host machine
    environment:
      # Override application.yml settings
      SPRING_PROFILES_ACTIVE: dev # Use application-dev.yml
      SPRING_DATA_MONGODB_URI: mongodb://admin:admin123@mongodb:27017/elearning_courses_db?authSource=admin
      # WHY mongodb as hostname? Docker network service discovery
      # Note: Inside Docker network, MongoDB still uses port 27017
    depends_on:
      mongodb:
        condition: service_healthy # Wait for MongoDB to be ready
    networks:
      - elearning-network
    restart: unless-stopped

# ===================================
# NETWORKS
# ===================================
networks:
  elearning-network:
    driver: bridge # Default network type
    # WHY? Isolates our services, allows inter-service communication

# ===================================
# VOLUMES
# ===================================
volumes:
  postgres-data:
    # Named volume - managed by Docker
    # WHY? Data persists even if container is deleted
    driver: local
  mongodb-data:
    # MongoDB data persistence
    driver: local
# ===================================
# FUTURE SERVICES (commented out)
# ===================================
# Add more services as we build them:
# - api-gateway
# - course-service (with MongoDB)
# - redis
# - rabbitmq
# - elasticsearch
