spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      # Global CORS configuration
      globalcors:
        cors-configurations:
          "[/**]":
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders: "*"
            exposedHeaders:
              - Authorization
            allowCredentials: false
            maxAge: 3600

      # Route configurations
      routes:
        # User Service Routes
        - id: user-service
          uri: http://user-service:8081
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=0

        # User Service Auth Routes
        - id: user-auth-service
          uri: http://user-service:8081
          predicates:
            - Path=/api/users/auth/**
          filters:
            - StripPrefix=0

        # Course Service Routes
        - id: course-service
          uri: http://course-service:8082
          predicates:
            - Path=/api/courses/**
          filters:
            - StripPrefix=0

        # Enrollment Service Routes
        - id: enrollment-service
          uri: http://enrollment-service:8083
          predicates:
            - Path=/api/enrollments/**
          filters:
            - StripPrefix=0

        # Progress Service Routes
        - id: progress-service
          uri: http://progress-service:8084
          predicates:
            - Path=/api/progress/**
          filters:
            - StripPrefix=0

# Server configuration
server:
  port: 8080

# JWT Configuration
jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000

# Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always

# Logging
logging:
  level:
    root: INFO
    com.elearning.gateway: DEBUG
    org.springframework.cloud.gateway: DEBUG
