# Development Profile Configuration
# This file is loaded when spring.profiles.active=dev

spring:
  data:
    mongodb:
      # Development MongoDB (Docker container on port 27017 internally)
      uri: mongodb://admin:admin123@mongodb:27017/elearning_progress_db?authSource=admin
    redis:
      # Development Redis (Docker container on port 6379)
      host: redis
      port: 6379

# Development logging - more verbose
logging:
  level:
    root: INFO
    com.elearning.progress: DEBUG
    org.springframework.data.mongodb: DEBUG
    org.springframework.web: DEBUG # See all HTTP requests/responses
  file:
    name: logs/progress-service-dev.log

# Development server configuration
server:
  error:
    include-message: always # Show error messages in response
    include-binding-errors: always # Show validation errors
    include-stacktrace: on_param # Show stacktrace with ?trace=true
    include-exception: true # Include exception class name

# Development service URLs (Docker network)
enrollment:
  service:
    url: http://enrollment-service:8083

course:
  service:
    url: http://course-service:8082
